import "../scss/main.scss"
import BootstrapClient from "./Components/BootstrapClient";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className="overflow-x-hidden">{children}</body>
      <BootstrapClient/>
    </html>
  );
}
